#!/bin/bash

DUCKIETOWN_DUCKIEBOT_PKG_DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
PACKAGES_DIR="${DUCKIETOWN_DUCKIEBOT_PKG_DIR}/.."

# Install default missions
# - check if the data package is installed
DATA_PKG_DIR="${PACKAGES_DIR}/data"
if [ ! -d "${DATA_PKG_DIR}" ]; then
  echo "Package 'data' not found."
  exit 101
fi

# - create destination database (if not present)
DB_DIR="${DATA_PKG_DIR}/data/private/databases/duckietown_duckiebot_missions"
mkdir -p $DB_DIR

# - install missions
MISSIONS_DIR="${DUCKIETOWN_DUCKIEBOT_PKG_DIR}/data/private/default_missions"
cp $MISSIONS_DIR/* $DB_DIR
